### ISSUE TITLE
SQL: Default path for tables in BQ is wrong

### ISSUE THREAD

**Issue by dqmota** [totvslabs/pyCarol#564]
While running a query without a table full path, the following error occurs:
`google.api_core.exceptions.NotFound: 404 Not found: Dataset labs-app-mdm-production:95e32d29dc62408d87689fca12e2449e was not found in location US`

A full path example:
`carol-95e32d29dc62408d8768.95e32d29dc62408d87689fca12e2449e.stg_localproteus_sa1t10`

**Comment by rafarui** [comment]
> While running a query without a table full path, the following error occurs: `google.api_core.exceptions.NotFound: 404 Not found: Dataset labs-app-mdm-production:95e32d29dc62408d87689fca12e2449e was not found in location US`
> 
> A full path example: `carol-95e32d29dc62408d8768.95e32d29dc62408d87689fca12e2449e.stg_localproteus_sa1t10`



> While running a query without a table full path, the following error occurs: `google.api_core.exceptions.NotFound: 404 Not found: Dataset labs-app-mdm-production:95e32d29dc62408d87689fca12e2449e was not found in location US`
> 
> A full path example: `carol-95e32d29dc62408d8768.95e32d29dc62408d87689fca12e2449e.stg_localproteus_sa1t10`

Carol does not provide an API to pycarol solve the dataset id when using the new BQ integration, I added a parameter to overwrite the default. in you case please use 

```python
df = SQL(Carol()).query(query, dataframe=True, method='bigquery',
    service_account=service_account, dataset_id='carol-95e32d29dc62408d8768.95e32d29dc62408d87689fca12e2449e' )
```

PS: this will be live after we merge the PR above.
