### ISSUE TITLE
query BQ with paging

### ISSUE THREAD

**Issue by darolt** [totvslabs/pyCarol#569]
We should provide an interface to BQ for paging queries. That should be close to what we have now for filter (query and named_query). We can use this thread to define it. I suggest:
on pycarol.bigquery:

query(query: str, page_size: Optional[int], ...) -> Tuple[Result, job_id]
page(job_id: Optional[str], page: Optional[int], ...) -> Result

Result is either a dict or a pandas DataFrame according to the other arguments.

what do you think @rafarui @JuvenalDuarte ?

**Comment by rafarui** [comment]
> We should provide an interface to BQ for paging queries. That should be close to what we have now for filter (query and named_query). We can use this thread to define it. I suggest: on pycarol.bigquery:
> 
> query(query: str, page_size: Optional[int], ...) -> Tuple[Result, job_id] page(job_id: Optional[str], page: Optional[int], ...) -> Result
> 
> Result is either a dict or a pandas DataFrame according to the other arguments.
> 
> what do you think @rafarui @JuvenalDuarte ?

very durable.. they even have an interface for us to use. 
https://cloud.google.com/bigquery/docs/samples/bigquery-query-pagination

**Comment by darolt** [comment]
Juvenal already have implemented this in carolina. I suggest that he takes this.

**Comment by darolt** [comment]
one concern of mine is that we need to maintain two APIs now:
bigquery.BQ.query
and SQL.query

**Comment by darolt** [comment]
Closing all old issues. If required we can open them again.
